"""
No: 12
Date: 11-15-2020

Problem:
    Spot the Difference
    You are given two strings, s and t which only consist of lowercase letters. 
    t is generated by shuffling the letters in s as well as potentially adding 
    an additional random character. Return the letter that was randomly added to 
    t if it exists, otherwise, return ’ ‘.
    Note: You may assume that at most one additional character can be added to t.

TestCases:
    s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''

Time Complexity:
    O(n+m)
Space Complexity:
    O(max(n,m)) 
"""


def spotTheDifference(s, t):
    hash = {}
    for char in t:
        if char in hash:
            hash[char] += 1
        else:
            hash[char] = 1
    for char in s:
        if char in hash:
            hash[char] -= 1

    for char in hash:
        if hash[char]:
            return char

    return ""


tests = [
    ["foobar", "barfoot", "t"],
    ["ide", "idea", "a"],
    ["coding", "ingcod", ""],
]

for index, test in enumerate(tests):
    res = spotTheDifference(test[0], test[1])
    assert res == test[2], "Test {}: found `{}`, should be `{}`".format(
        index, res, test[2]
    )
